---
- name: Install and Run Node.js App
  hosts: localhost
  become: yes
 
  tasks:
    - name: Updat yum package cache
      yum:
        update_cache: yes
      become: yes
 
    - name:  Node.js and npm
      yum:
        name:
          - nodejs
          - npm
        state: present
      become: yes
  
    - name: Install app dependencies using package.json
      command: npm install /var/lib/awx/projects/_10__rhel_app/package.json    
      become: yes
 
    - name: Run Node.js app
      command: node /var/lib/awx/projects/_10__rhel_app/src/server.mjs 
      
      become: yes