---
- name: Install and Run Node.js App
  hosts: localhost
  become: yes
 
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      become: yes
 
    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present
      become: yes
  
    - name: Install app dependencies using package.json
      command: npm install      
      become: yes
 
    - name: Run Node.js app
      command: node ./src/server.mjs
      
      become: yes